### ISSUE TITLE
Hung up on a file

### ISSUE THREAD

**Issue by lasers** [simonsolnes/ls-acid#7]
I notice that if I `lsr ~/Download` directory, `lsr` get hung up on a `37M` ASCII text file. Maybe it is too much for the script to deal with... I get stuck right there for more than two minutes before I `^C`.

I already reached `100%` on `htop` with this script.

I'm not sure what the script does, but `lsr` should explicitly read first few lines instead of going through the whole thing... 711102 lines according to `wc -l`... which I think may be the reason I'm stuck here.

**Comment by simonsolnes** [comment]
Haha omg. That is not good. Yeah, it's very controversial, but this program is actually going to check every single line of every file at the moment. I will work on making it stop when it realises it's going to far.

**Comment by simonsolnes** [comment]
I created an option for it: https://github.com/simonsolnes/ls-acid/commit/59c3ec51f8b01631ef4e86613cd43033af7060fe
